Traceback (most recent call last):
  File "/Users/alexandercai/micromamba/envs/rlbook/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/alexandercai/micromamba/envs/rlbook/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alexandercai/micromamba/envs/rlbook/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alexandercai/micromamba/envs/rlbook/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/alexandercai/micromamba/envs/rlbook/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/alexandercai/micromamba/envs/rlbook/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/alexandercai/micromamba/envs/rlbook/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
agent = ExploreThenCommit(mab.K, mab.T, mab.T // 15)
mab_loop(mab, agent)
plot_strategy(mab, agent)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[13], line 2[0m
[1;32m      1[0m agent [38;5;241m=[39m ExploreThenCommit(mab[38;5;241m.[39mK, mab[38;5;241m.[39mT, mab[38;5;241m.[39mT [38;5;241m/[39m[38;5;241m/[39m [38;5;241m15[39m)
[0;32m----> 2[0m [43mmab_loop[49m[43m([49m[43mmab[49m[43m,[49m[43m [49m[43magent[49m[43m)[49m
[1;32m      3[0m plot_strategy(mab, agent)

File [0;32m~/Documents/latexify_py/src/latexify/ipython_wrappers.py:38[0m, in [0;36mLatexifiedRepr.__call__[0;34m(self, *args)[0m
[1;32m     37[0m [38;5;28;01mdef[39;00m [38;5;21m__call__[39m([38;5;28mself[39m, [38;5;241m*[39margs) [38;5;241m-[39m[38;5;241m>[39m Any:
[0;32m---> 38[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_fn[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m)[49m

Cell [0;32mIn[4], line 4[0m, in [0;36mmab_loop[0;34m(mab, agent)[0m
[1;32m      1[0m [38;5;129m@latex[39m
[1;32m      2[0m [38;5;28;01mdef[39;00m [38;5;21mmab_loop[39m(mab: MAB, agent: [38;5;124m"[39m[38;5;124mAgent[39m[38;5;124m"[39m) [38;5;241m-[39m[38;5;241m>[39m [38;5;28mint[39m:
[1;32m      3[0m     [38;5;28;01mfor[39;00m t [38;5;129;01min[39;00m [38;5;28mrange[39m(mab[38;5;241m.[39mT):
[0;32m----> 4[0m         arm [38;5;241m=[39m [43magent[49m[38;5;241;43m.[39;49m[43mchoose_arm[49m[43m([49m[43m)[49m  [38;5;66;03m# in 0, ..., K-1[39;00m
[1;32m      5[0m         reward [38;5;241m=[39m mab[38;5;241m.[39mpull(arm)
[1;32m      6[0m         agent[38;5;241m.[39mupdate_history(arm, reward)

Cell [0;32mIn[12], line 7[0m, in [0;36mExploreThenCommit.choose_arm[0;34m(self)[0m
[1;32m      6[0m [38;5;28;01mdef[39;00m [38;5;21mchoose_arm[39m([38;5;28mself[39m):
[0;32m----> 7[0m     [38;5;28;01mreturn[39;00m [43msolution[49m[38;5;241m.[39metc_choose_arm([38;5;28mself[39m)

[0;31mNameError[0m: name 'solution' is not defined

